site_name: Moje projekty
site_author: Marcin Turczyk
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: Marcin-git99/ds_ai_portfolio
repo_url: https://github.com/Marcin-git99/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: blue

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Titanic": tytanic/index.md
- Poprzednie projekty:
  - "Iris": iris/index.md
